apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: helm-chart-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: source-repo
      type: string
    - name: source-branch
      type: string
    - name: helm-chart-path
      type: string
    - name: oci-registry
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.source-repo)
        - name: revision
          value: $(params.source-branch)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: package-helm-chart
      taskRef:
        name: package-helm-chart
      params:
        - name: helm-chart-path
          value: $(params.helm-chart-path)
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - git-clone

    - name: sign-helm-chart
      taskRef:
        name: sign-helm-chart
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - package-helm-chart

    - name: push-helm-chart
      taskRef:
        name: push-helm-chart
      params:
        - name: oci-registry
          value: $(params.oci-registry)
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - sign-helm-chart
