apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gitlab-webhook
  
spec:
   
  to:
    kind: Service
    name: el-gitlab-listener
    weight: 100
  port:
    targetPort: http-listener
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
