apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
    - name: git-repo-url
    - name: git-revision
    - name: helm-chart-path
    - name: oci-registry
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: helm-chart-pipeline-run-
      spec:
        pipelineRef:
          name: helm-chart-pipeline
        params:
          - name: source-repo
            value: $(tt.params.git-repo-url)
          - name: source-branch
            value: $(tt.params.git-revision)
          - name: helm-chart-path
            value: $(tt.params.helm-chart-path)
          - name: oci-registry
            value: $(tt.params.oci-registry)
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: pipeline-pvc
