apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: gitlab-binding
spec:
  params:
    - name: git-url
      value: $(body.project.git_http_url)
    - name: git-revision
      value: $(body.checkout_sha)
    - name: helm-chart-path
      value: charts/my-chart
    - name: oci-registry
      value: oci://example.com/my-helm-charts
