apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: gitlab-binding
spec:
  params:
    - name: git-repo-url
      value: $(body.repository.git_http_url)
    - name: git-revision
      value: $(body.after)
    - name: helm-chart-path
      value: "simplechart"
    - name: oci-registry
      value: "oci://example.com/my-helm-charts"
